#!/usr/bin/env bash

BATT=$(acpi -b | sed 's/.*[charging|unknown], \([0-9]*\)%.*/\1/gi')
DATE=$(date '+%D')
HOUR=$(date '+%H:%M')
SOUND_VOLUME=$(amixer get Master | grep "Left:" | awk {'print $5'} | sed 's/\[\|\]//g')
SOUND_STATUS=$(amixer get Master | grep "Left:" | awk {'print $6'} | sed 's/\[\|\]//g')
WIRELESS=$([[ "$(iwgetid -r)" == "" ]] && printf "Disconnected" || printf "$(iwgetid -r)")
BRIGHTNESS=$(light)

if [[ $(acpi -b | sed 's/.*: \([a-zA-Z]*\),.*/\1/gi') == "Discharging" ]]; then
    BATT_ICON="↓"
else
    BATT_ICON="↑"
fi

xsetroot -name " V: $SOUND_VOLUME ${SOUND_STATUS^^} | W: $WIRELESS | B:$BRIGHTNESS | BATT: $BATT% $BATT_ICON | $DATE | $HOUR "
